steps:
  # Build and Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Frontend'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend:3.0.0', './frontend']
    
  # Build and Push Orders Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Orders'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/orders:3.0.0', './orders']

  # Build and Push Products Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Products'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/products:3.0.0', './products']

# List of images that will be pushed to the registry
images:
  - 'gcr.io/$PROJECT_ID/frontend:3.0.0'
  - 'gcr.io/$PROJECT_ID/orders:3.0.0'
  - 'gcr.io/$PROJECT_ID/products:3.0.0'
