version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - orders
      - products

  orders:
    build:
      context: ./orders
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

  products:
    build:
      context: ./products
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
