version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/app/src
    networks:
      - mern-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
    networks:
      - mern-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - mern-network

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network

volumes:
  mongo-data:

networks:
  mern-network: