version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "${PORT}:${PORT}"
    networks:
      - mern-network
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: ${MONGO_URI}
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - mern-network

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./frontend/build:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - mern-network

  mongo:
    image: bitnami/mongodb:6.0-debian-11
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-network
    environment:
      MONGODB_ROOT_USER: ${MONGO_ROOT_USER}
      MONGODB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGODB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo-data:/bitnami/mongodb

volumes:
  mongo-data:

networks:
  mern-network:
    driver: bridge
